import type { Metadata } from "next";
import { Inter } from "next/font/google";
import QueryProvider from "./QueryProvider";
import Footer from "./components/ui/footer/Footer";
import Header from "./components/ui/header/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amir Meberbeche: Développeur web Junior",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <QueryProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
