import type { Metadata } from "next";
import { Inter } from "next/font/google";
import QueryProvider from "./QueryProvider";
import ReduxStoreProvider from "./ReduxStoreProvider";
import Footer from "./components/ui/footer/Footer";
import Header from "./components/ui/header/Header";
import Modal from "./components/ui/modalComponent/Modal";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Amir Meberbeche: Développeur web Junior",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <ReduxStoreProvider>
          <QueryProvider>
            <Modal />
            <Header />
            {children}
            <Footer />
          </QueryProvider>
        </ReduxStoreProvider>
      </body>
    </html>
  );
}
